
-- SCRIPT DE CRIAÇÃO DO BANCO DE DADOS

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'cliente'))
BEGIN
    CREATE TABLE cliente (
    ClienteID int IDENTITY(1,1) PRIMARY KEY,
    Nome varchar(255) NOT NULL
);
END
GO


